### ISSUE TITLE
Add proxies to requests.

### ISSUE THREAD

**Issue by Cald-fan** [suufi/noblox.js#103]
When making a lot of requests you will get an error saying,
`UnhandledPromiseRejectionWarning: RequestError: Error: ETIMEDOUT`.
And it will keep requests from going through, proxies will fix this.

**Comment by Neztore** [comment]
Hi Cald-fan , if you're making so many requests that you start getting errors I suggest you make less requests or properly limit the number you are making.
What you are suggesting is that we make a change purely to support your abuse of the Roblox API, so that you can circumvent the rate limit.
An easy solution is to make use of `Async Await` functions to slow things down, or use `setInterval`/`setTimeout` to space out your API Requests.
