### ISSUE TITLE
[BUG] Bot returns error 'Role does not exist' even though it clearly does when ranking?

### ISSUE THREAD

**Issue by ajtube2017** [suufi/noblox.js#175]
So I'm making a simple bot to test my skills and learn a bit of JS, so I decided to branch off my bot into automating functions (like ranking a user or sending a shout), I've seen this post before about a year ago, but it seems I'm getting the error still, it's probably something I did wrong but here's my code. 
```javascript

                console.log('I\'m doing something.');
               nbx.getIdFromUsername(`${args[0]}`).then((getIdFromUsername) => {
                userid = getIdFromUsername
                console.log(`${args[0]} + ${args[1]}`);
                nbx.setRank(group, userid, args[1] ); // This is the main line of course.
              });
    
```
So this is a simple few lines of code of course, but when I run it argument 1 is still 1 like I sent in the message, but for some reason that isn't the case?
Also a little bit more information that *might* be the issue;
I'm ranking myself (owner of the group) to role 1

**Comment by ajtube2017** [comment]
Yeah, so I came back to it later and it turned out that if I set the rank to 1 instead it worked, sorry about that. Still not sure why it's doing that but I'll keep you updated.

**Comment by Neztore** [comment]
Hi! setRank does not accept a rank number (1-255), but a roleset when passed in this way.

Why not try passing it like so:
```js
nbx.setRank({ group, target: userid, rank: args[1] })
```

[Relevant docs page](https://noblox.js.org/#set-rank)

**Comment by zachariapopcorn** [comment]
> Hi! setRank does not accept a rank number (1-255), but a roleset when passed in this way.
> 
> Why not try passing it like so:
> 
> ```js
> nbx.setRank({ group, target: userid, rank: args[1] })
> ```
> 
> [Relevant docs page](https://noblox.js.org/#set-rank)

It seems to rank just fine when I do nbx.setRank(<group>, <user>, 4)

**Comment by xAtomik** [comment]
> Yeah, so I came back to it later and it turned out that if I set the rank to 1 instead it worked, sorry about that. Still not sure why it's doing that but I'll keep you updated.

The reason this is happening is because your `args[1]` is a `string`. Due to a `strict equal` operator in [getRole.js](https://github.com/suufi/noblox.js/blob/master/lib/group/getRole.js#L35) this means it will not match a `string` against a `number` (which it is expecting).
To fix your issue, I would recommend instead of using `args[1]`, use `Number.parseInt(args[1]`. That should make the passed argument a number and find the role correctly. 😄

**Comment by GamerGG1** [comment]
Hi combo never reply as much Sent from my T-Mobile 4G LTE Tablet
-------- Original message --------From: Atom <notifications@github.com> Date: 8/10/20  16:35  (GMT+03:00) To: "suufi/noblox.js" <noblox.js@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [suufi/noblox.js] [BUG] Bot returns error 'Role does not exist'
  even though it clearly does when ranking? (#175) 



Yeah, so I came back to it later and it turned out that if I set the rank to 1 instead it worked, sorry about that. Still not sure why it's doing that but I'll keep you updated.



The reason this is happening is because your args[1] is a string. Due to a strict equal operator in getRole.js this means it will not match a string against a number (which it is expecting).

To fix your issue, I would recommend instead of using args[1], use Number.parseInt(args[1]. That should make the passed argument a number and find the role correctly. 😄



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/suufi/noblox.js/issues/175#issuecomment-671357814",

"url": "https://github.com/suufi/noblox.js/issues/175#issuecomment-671357814",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
