### ISSUE TITLE
ROBLOX Login Captcha

### ISSUE THREAD

**Issue by BloxDaCoder** [suufi/noblox.js#22]
Help needed asap! My bot cannot login to roblox due to a captcha. I do not know how to solve it.

**Comment by suufi** [comment]
Are you sure it's a captcha?

**Comment by Shark3900** [comment]
Assuming BloxDaCoder is talking about the same thing that's been effecting my bot since sometime last night, attempting to login to ROBLOX is continuously returning this error (unless he's not which has some very coincidental timing):

![powershell_2018-08-30_22-06-14](https://user-images.githubusercontent.com/18512662/44907789-28fea500-ace7-11e8-80b3-a36261f05a31.png)

**Comment by LapinoLapidus** [comment]
Shark's issue is reproducable with the same error message

**Comment by LapinoLapidus** [comment]
PR #21 Seems to fix this issue for me
