### ISSUE TITLE
[BUG] Noblox doesn't send messages to users even though the promise doesn't get rejected

### ISSUE THREAD

**Issue by zachariapopcorn** [suufi/noblox.js#227]
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

**Describe the bug**
Noblox doesn't reject the promise used by noblox.message(...) yet it failed to send the DM to the user supplied on Roblox 

**To Reproduce**
Use a try-catch block using the function and if you set it up to log an error message on error, it won't log regardless if there's an error or not

**Expected behavior**
It logs to the console if there was an error message

**Code**
The code that I'm using is the following
```js
let groupName = (await roblox.getGroup(configFile.groupID)).name
let didError = false;
try {
await roblox.message(rbxID, "Change Rank", `Your rank in the group ${groupName} has been changed from ${oldRankName} (${oldRankID}) to ${newRankName} (${newRankID}) by ${await roblox.getUsernameFromId(authorID)} (${authorID})`);
} catch (err) {
console.log("Errored");
didError = true;
}
console.log(didError);
if(didError == true) {
message.channel.send(embedMaker('Error', `Due to the bot's settings in the configuration file, the bot was supposed to message this user on Roblox about this action, but there was an error: ${err}`));
} else {
message.channel.send(embedMaker('Sent', `Due to the bot's settings in the configuration file, this action was reported to the user in question on Roblox via DMs`));
}
```

When I do console.log(didError) it says it's false, but it should be true

**Comment by Neztore** [comment]
Roblox uses DSN blocking to prevent hosts (E.g. Digital ocean, Glitch AWS, to name a few) from doing some things like sending messages. It's to stop abuse.

Noblox.js should reject; I suspect Roblox is returning a 200 when it really should not be.
You can see [here](https://github.com/suufi/noblox.js/blob/master/lib/user/message.js#L37) that it only resolves (instead of rejecting) if it is returned status 200. 

Edit your code to log what is returned i.e.:
````js
const res = await roblox.message(...);
``` and reply with what res is.

----
As mentioned above, I don't think is something we can easily control for - Roblox is intentionally not telling us that it's failing (I think)
My immediate recommendation is not to rely on Roblox messages in production. They're filtered, and roblox really doesn't want us using them.
If you could tell me what the body is, and it's something useful like an error, we might be able to fix this.

**Comment by zachariapopcorn** [comment]
I'm not hosting it though, only using my computer. I decided that I'll just use a raw http request instead of roblox.message().

**Comment by suufi** [comment]
One option we do have is checking the `SentMessages` with `getMessages`.
