### ISSUE TITLE
How2Made A Anti Adverting For My Group

### ISSUE THREAD

**Issue by mollomm2** [suufi/noblox.js#233]
Hi I Want Made A Anti-Adverting Bot For My Roblox Group (Bot Just Remove Post If I Contain A Link (roblox.com))

Please What The Code I Do Use ?

**Comment by Neztore** [comment]
Hi!
Your question is not related to Noblox - you've asked us "how do I do X".
See our docs: https://noblox.js.org, [onWallPost](https://noblox.js.org/#group-events) may help you.

You could use String.includes and the wall post functions, however your issue is invalid. 
Use Google. You may also want to [join the discord](https://discord.gg/EDXNdAT).

---

In future, issues like these will be closed without comment. Please look at our docs before asking questions,
Thanks!
