### ISSUE TITLE
I Suggest adding this feature, noblox.checkJoinRequest(groupID, userID)

### ISSUE THREAD

**Issue by happygagarara12** [suufi/noblox.js#247]
**Is your feature request related to a problem? Please describe.**
My feature request related to a problem, if don't add this feature it will cause a misunderstanding to my bot. My bot will accept the user join request and say `Success! accepted [user] join request!` even when the userID provided was not in the join request. it will throw an error too in the console and I tried to handle the error but it didn't work

**Describe the solution you'd like**
I suggest this like example `noblox.checkJoinRequest(groupID, userID)` and it will return `true` if the USER is in the group join request but return `false` if the user is not in the group join request.

**Describe alternatives you've considered**
There is no alternative

**Additional context**
https://groups.roblox.com/docs#!/Membership/get_v1_groups_groupId_join_requests_users_userId

That is the API for these suggestions

Thanks!

**Comment by XoAlone** [comment]
Lol you can handle the error easily, it works but you just don't know how to do it.

**Comment by ChrisvanChip** [comment]
An alternative would be a `try...catch` block, you can read more about that [here (MDN web docs)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch). 

You can initiate a variable like `success` and set it on `false` firstly. Then, use the `try...catch` block to execute the join request. If no error is returned, set the variable `success` on `true`, otherwise do nothing. Below the `try...catch` block, you can use an `if...else` statement to check if `success` is `true` or `false` and write the appropriate message for the result.

**Comment by suufi** [comment]
This seems rather redundant to be fair. `getJoinRequests` does exist which you can check to see if there already exists a join request given a `userId`.
