### ISSUE TITLE
[BUG] addDeveloperProduct throws an error.

### ISSUE THREAD

**Issue by doodDotJS** [suufi/noblox.js#313]
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

**Describe the bug**
When calling addDeveloperProduct with the appropriate arguments, an error is thrown saying "You are not logged in!". I did some investigation in my own and found out that `jar` is undefined in `checkDeveloperProductName.js`

**To Reproduce**
1. Login using a token.
2. Call addDeveloperProduct with the appropriate args and wrap it around a `try..catch` and console.log the error.
3. Look in the console.

**Expected behavior**
I expected it to create a developer product and return a `DeveloperProductAddResult`

**Comment by alanbixby** [comment]
You must be authenticated to create a developer product. That error is because you are not calling and awaiting `setCookie()` before calling `addDeveloperProduct()`. This would be the case for _any_ of our authenticated methods.

Using snippets from the documentation's [Getting Started](https://noblox.js.org/index.html), and [method examples](https://noblox.js.org/global.html#addDeveloperProduct):

```js
const noblox = require('noblox.js')
const COOKIE = ''

async function startApp () {
  await noblox.setCookie(process.env.COOKIE || COOKIE)
  const { UniverseId } = await noblox.getPlaceInfo(6480087726) // Replace with the placeId you want to create the developer product in
  const developerProduct = await noblox.addDeveloperProduct(UniverseId, 'Developer Product Name', 1234, 'A developer product made using noblox')
  console.log(developerProduct)
}

startApp()
```

should return a response along the lines of:

```js
{
  universeId: 2421261122,
  name: 'Developer Product Name',
  priceInRobux: 1234,
  description: 'A developer product made using noblox',
  productId: 1163015605
}
```

You only need to call `setCookie()` once, and it must be _before_ calling an authenticated endpoint.

---

**NOTE:** It appears our current implementation doesn't support images yet. The method is using a `www.` endpoint, and they generally lack stability/documentation. I'll look into reverse engineering how images are handled for it and likely make a PR for that.

**Comment by doodDotJS** [comment]
I found out what I was doing wrong. I put the universe ID incorrectly. Sorry!
