### ISSUE TITLE
The group payout not work and still get bad request!

### ISSUE THREAD

**Issue by outapzaza** [suufi/noblox.js#78]
I dont know why what i do wrok it still give me bad request here this is my code

const roblox = require('noblox.js')
const cookie = tempVars('cookie')
const group = tempVars("groupid")
const user = tempVars("userid")
const robux = tempVars("rbx")

 roblox.cookieLogin(cookie)
    .then(function() { 
        console.log('Logged on.') 
        roblox.groupPayout(group, user, [robux])
    })
    .catch(function(error) { 
        console.log(error) 
    });
 

dont care about [robux] it very impotent the group api send me a info w/ []

so why it still give me bad request
![image](https://user-images.githubusercontent.com/40026698/62294480-31ca9e80-b495-11e9-8199-64134c3b36c0.png)

**Comment by outapzaza** [comment]
The code make for work w/ DBM

**Comment by policetonyR** [comment]
roblox.groupPayout(group, user, robuxamount)

**Comment by lordhammyrblx** [comment]
This is not the appropriate place to post issues about your code/improper usage of the library. Use the *Roblox API Discord Server*, specifically the channel for this library to ask such questions. https://discord.gg/EDXNdAT

You are getting *Bad Request* because you are sending an array for the robux parameter, the API expects a positive integer.
